version: '3.8'
services:
  vite-react-app:
    build:
      context: .
      args:
        NODE_ENV: development
    ports:
      - "5173:5173"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: ["yarn", "dev", "--host", "0.0.0.0"]
